Update BuildHomeProxySuite.yml

diff --git a/.github/workflows/BuildHomeProxySuite.yml b/.github/workflows/BuildHomeProxySuite.yml
--- a/.github/workflows/BuildHomeProxySuite.yml
+++ b/.github/workflows/BuildHomeProxySuite.yml
@@ -34,20 +34,30 @@ jobs:
           tar --use-compress-program=unzstd -xf ${SDK_ARCHIVE}
           mv ${SDK_DIRNAME} openwrt-sdk
 
-      - name: Add homeproxy feed
+      - name: Fetch homeproxy source
+        run: |
+          git clone https://github.com/immortalwrt/homeproxy.git src-homeproxy
+          cd src-homeproxy
+          git checkout "${{ github.event.inputs.homeproxy_ref }}"
+
+      - name: Place luci-app-homeproxy into SDK
+        run: |
+          if [ -d "src-homeproxy/luci-app-homeproxy" ]; then
+            cp -r "src-homeproxy/luci-app-homeproxy" "openwrt-sdk/package/luci-app-homeproxy"
+          else
+            echo "Missing luci-app-homeproxy directory" && exit 1
+          fi
+
+      - name: Update feeds and defconfig
         working-directory: openwrt-sdk
         run: |
-          echo "src-git homeproxy https://github.com/immortalwrt/homeproxy.git;${{ github.event.inputs.homeproxy_ref }}" >> feeds.conf.default
-          ./scripts/feeds update homeproxy
-          ./scripts/feeds install -a -p homeproxy
-
-      - name: Defconfig
-        working-directory: openwrt-sdk
-        run: make defconfig
+          ./scripts/feeds update -a
+          ./scripts/feeds install -a
+          make defconfig
 
       - name: Build luci-app-homeproxy (with i18n)
         working-directory: openwrt-sdk
-        run: make package/feeds/homeproxy/luci-app-homeproxy/compile V=s
+        run: make package/luci-app-homeproxy/compile V=s
 
       - name: Collect built packages
         id: collect
